// project mapping for legacy
module.exports.PROJECTS = {
  1: 'portunus',
  2: 'overseer',
  5: 'overlord',
  6: 'firstorder',
  7: 'snoke',
  8: 'keywarden',
  9: 'hub',
  10: 'flash-ias-authorization',
  12: 'flaat-api',
  13: 'covidata',
  14: 'anubis',
  15: 'camp-history-writer',
  16: 'algolia-sync',
  17: 'fusion-logs',
  18: 'popular-times',
  19: 'legion',
  20: 'enrichdata',
  21: 'ml-fusion',
}
