name: Publish Cloudflare Workers - dev environment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'dev-*' # release tag for on-demand deployment
    paths-ignore:
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: set node version according to .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          wranglerVersion: '3.2.0'
          command: deploy --env dev
          environment: dev
          secrets: |
            MAIL_PASS
            TOKEN_SECRET
            DETA_KEY
        env:
          # Sendgrid 'dev'
          MAIL_PASS: ${{ secrets.MAIL_PASS_DEV }}
          # JWT token secret 'dev'
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET_DEV }}
          # Deta 'dev' collection
          DETA_KEY: ${{ secrets.DETA_KEY_DEV }}
